export const HORSE_DISPLAY_NAMES = [
  'Ada Lovelace',
  'Grace Hopper',
  'Margaret Hamilton',
  'Joan Clarke',
  'Katherine Johnson',
  'Dorothy Vaughan',
  'Mary Jackson',
  'Radia Perlman',
  'Frances Allen',
  'Barbara Liskov',
  'Karen Spärck Jones',
  'Shafi Goldwasser',
  'Cynthia Breazeal',
  'Fei-Fei Li',
  'Reshma Saujani',
  'Hedy Lamarr',
  'Annie Easley',
  'Stephanie Shirley',
  'Megan Smith',
  'Parisa Tabriz',
] as const

export const HORSE_COLOR_LABELS = [
  'Red',
  'Blue',
  'Yellow',
  'Green',
  'Orange',
  'Purple',
  'Pink',
  'Brown',
  'Black',
  'White',
  'Cyan',
  'Magenta',
  'Navy',
  'Teal',
  'Lime',
  'Olive',
  'Maroon',
  'Silver',
  'Gold',
  'Violet',
] as const
